### ISSUE TITLE
Info Endpoint in Openai v1/model style

### ISSUE THREAD

**Issue by michaelfeil** [BerriAI/liteLLM-proxy#4]
It would be helpful to provide the information on which model is running.

**Comment by krrishdholakia** [comment]
Hey @michaelfeil - definitely. Can you tell me more about what you're trying to achieve?

**Comment by krrishdholakia** [comment]
what does 'which model is running' mean in that context? 

E.g. if you can call openai and anthropic via the server, would that mean both models are 'running'? 

And how is 'running' different from 'available'?
